///////////NODETYPE////////////////////
#define NODE_CONSTANT 0
#define NODE_VARIABLE  1
#define NODE_READ 2
#define NODE_WRITE 3
#define NODE_CONNECTOR 4
#define NODE_ADD 5
#define NODE_SUB 6
#define NODE_MUL 7
#define NODE_DIV 8
#define NODE_MOD 9
#define NODE_LT 10
#define NODE_GT 11
#define NODE_LTE 12
#define NODE_GTE 13
#define NODE_EQ 14
#define NODE_NE 15
#define NODE_IF 16
#define NODE_IF_BLOCK 17
#define NODE_WHILE 18
#define NODE_WHILE_BLOCK 19
#define NODE_REPEAT 20
#define NODE_REPEAT_BLOCK 21
#define NODE_DO 22
#define NODE_DOWHILE_BLOCK 23
#define NODE_BREAK 24
#define NODE_CONTINUE 25
#define NODE_INT 26
#define NODE_STRING 27
#define NODE_STRINGS 28
#define NODE_VAR_ARRAY 29
#define NODE_VAR_PARAMLIST 30
#define NODE_ASSG_EQ 31
#define NODE_VAR_FUNC_CALL 32
#define NODE_ARGLIST 33
#define NODE_MAIN 34
#define NODE_RETURN 35
#define NODE_PARAM 36
#define NODE_PARAM_VARIABLE 37
#define NODE_LCONNECTOR 38
#define NODE_FUNCTION 39
#define NODE_MCONNECTOR 40
#define NODE_AND 41
#define NODE_OR 42
#define NODE_NOT 43

//////TYPE OF THE VARIABLE//////////////
#define booltype 0
#define intType 1
#define stringType 2